version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file: .env
  web:
    build: .
    command: rails s -p 3030 -b '0.0.0.0'
    env_file: .env
    volumes:
      - .:/myapp
    ports:
      - "3030:3030"
    depends_on:
      - db
